"""
Sandboxed Python execution for the Coding Sub-Agent.

Used for on-the-fly derived calculations the structured-data SQL layer isn't
well suited to (e.g. "what CAGR would get Havenbrook Seltzer from its FY23 revenue to
$5M by FY28?", custom multi-step arithmetic, ad-hoc aggregation of numbers
already retrieved by other sub-agents, simple matplotlib charts).

SANDBOXING APPROACH (documented trade-off in docs/DESIGN_DECISIONS.md):
  - Runs in-process with a restricted `__builtins__` allowlist (no `open`,
    `import`, `exec`, `eval`, `__import__`, `input`, filesystem or subprocess
    access) and a small allowlisted set of safe modules (math, statistics,
    datetime) injected directly as names.
  - A wall-clock timeout via a hard signal alarm (SIGALRM) kills runaway
    loops. This is a same-process, resource-limited sandbox suitable for a
    prototype/demo; it is explicitly NOT a hardened multi-tenant sandbox
    (that would mean a subprocess/container with cgroup limits and a real
    seccomp policy, which we flag as a "production hardening" follow-up
    rather than build under this deadline).
  - The code string itself is generated by the LLM from the user's question,
    never taken verbatim from raw user input, and results (not the code) are
    what get shown to the user by default -- but the code is also surfaced
    for transparency ("Support transparent reporting of assumptions").
"""
from __future__ import annotations
import io
import contextlib
import signal
import math
import statistics
import datetime
from dataclasses import dataclass

TIMEOUT_SECONDS = 5

SAFE_GLOBALS = {
    "__builtins__": {
        "abs": abs, "round": round, "min": min, "max": max, "sum": sum, "len": len,
        "range": range, "enumerate": enumerate, "zip": zip, "sorted": sorted,
        "list": list, "dict": dict, "set": set, "tuple": tuple, "float": float,
        "int": int, "str": str, "bool": bool, "print": print,
    },
    "math": math, "statistics": statistics, "datetime": datetime,
}


class CodeExecutionError(RuntimeError):
    pass


@dataclass
class CodeResult:
    ok: bool
    stdout: str = ""
    result: object = None
    error: str = ""


def _timeout_handler(signum, frame):
    raise TimeoutError(f"Execution exceeded {TIMEOUT_SECONDS}s timeout.")


def run_code(code: str) -> CodeResult:
    """Executes `code`, which must assign its final answer to a variable
    named `result`. stdout is captured separately for transparency."""
    local_vars: dict = {}
    stdout_buf = io.StringIO()
    old_handler = None
    try:
        old_handler = signal.signal(signal.SIGALRM, _timeout_handler)
        signal.alarm(TIMEOUT_SECONDS)
        with contextlib.redirect_stdout(stdout_buf):
            exec(code, dict(SAFE_GLOBALS), local_vars)
        return CodeResult(ok=True, stdout=stdout_buf.getvalue(), result=local_vars.get("result"))
    except TimeoutError as e:
        return CodeResult(ok=False, error=str(e))
    except Exception as e:
        return CodeResult(ok=False, stdout=stdout_buf.getvalue(), error=f"{type(e).__name__}: {e}")
    finally:
        signal.alarm(0)
        if old_handler is not None:
            signal.signal(signal.SIGALRM, old_handler)
